#!/bin/sh
help() {
echo "install-sv - install a OpenRC service"
echo "Usage: install-sv [service]"
echo "Install service files to /etc/init.d /etc/conf.d"
echo "For many services inside a directory, find it in"
echo "$sysroot/$prefix/share/openrc-services/<sv>"
echo "All service files are provided by Artix Linux"
}

if test -z $sysroot; then
	sysroot=/ 
fi

if test -z $prefix; then
	prefix=/usr
fi

if test -z "${1}"; then
	help 
fi

svdir="$sysroot/$prefix/share/openrc-services/"

for x in $*; do
	if ! test -d $svdir/$x/; then
		echo "Service $x not found!"
		exit 1
	fi
	install -Dvm755 $svdir/$x/init.d/$x $sysroot/etc/init.d/$x 
	if test -f $svdir/$x/conf.d/$x; then
		install -Dvm755 $svdir/$x/conf.d/$x $sysroot/etc/conf.d/$x
	fi
done
