#!/bin/sh

if test -z "$1"; then 
	echo "iso-elfboot - Generate a elfboot compatible iso9660"
	echo "Usage: iso-elfboot [CD root] [output] [label] [elfboot-config]"
	exit 0
fi

if test -z "$elfbootdir"; then
	elfbootdir=/usr/share/elfboot
fi

for x in bootimg.bin elfboot.bin \
	elfboot.bid elfboot.tmg \
	elfboot.map modules; do 
cp -r $sysroot/$elfbootdir/$x $1/$x || exit 1 
done

cp -r $4 $1/elfboot.cfg

xorriso -as mkisofs \
	-b bootimg.bin \
	-no-emul-boot \
	-volid "$3" \
	-boot-info-table \
	--sort-weight 6 bootimg.bin \
	--sort-weight 5 elfboot.bin \
	--sort-weight 4 elfboot.bid \
	--sort-weight 3 elfboot.tmg \
	--sort-weight 2 elfboot.map \
	--sort-weight 1 modules \
	-full-iso9660-filenames \
	-o $2 \
	$1 || exit 1
echo "Done ISO generated at $2" 
